[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "step-hitl"
version = "0.0.1"
description = "An app template for Python REST-API's"
authors = [
    {name = "Bechtle AV360", email = "info@av360.io"}
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache License 2.0",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi>=0.115.11",
    "fastapi-mcp",
    "dynaconf>=3.2.6,<4.0",
    "prometheus_client>=0.21.0,<1.0",
    "uvicorn>=0.23.2",
    "idac_extractor>=0.2.1,<1.0",
    "idac_configurations>=0.3.18,<1.0",
    "idac_workspaces>=0.1.4,<1.0"    
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
    "pre-commit>=3.0.0",
]

[tool.black]
line-length = 120
target-version = ["py312"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
